version: '3.3'
services:
  node:
    container_name: i_happy-birthday-back
    image: 'node:19-alpine'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm run dev'
    ports:
      - '3002:3002'
    volumes:
      - './src:/home/node/app'